apiVersion: v2
name: cloudflare-tunnel
description: A Helm chart for deploying Cloudflare tunnel

type: application

version: 1.0.0

appVersion: "1.0.0"

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
